INSERT INTO Movie(title, year, posterurl, director, casts, genre)
VALUES 
('Kung Fu Panda',
2008,
'https://m.media-amazon.com/images/M/MV5BODJkZTZhMWItMDI3Yy00ZWZlLTk4NjQtOTI1ZjU5NjBjZTVjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
'Mark Osborne',
'Jack Black, Jackie Chen',
'Action, Comedy'),
('Kung Fu Panda 2',
2011,
'https://m.media-amazon.com/images/M/MV5BYzQ0ZWIxZjAtYWI3Yy00MGM0LWFjOGYtNzcyYThiOTA3ODI1XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
'Jennifer Yuh Nelson',
'Jack Black, Jackie Chen',
'Action, Comedy'),
('Kung Fu Panda 3',
2016,
'https://m.media-amazon.com/images/M/MV5BMTUyNzgxNjg2M15BMl5BanBnXkFtZTgwMTY1NDI1NjE@._V1_SX300.jpg',
'Alessandro Carloni',
'Jack Black, Jackie Chen',
'Action, Comedy'),
('Harry Potter and the Deathly Hallows: Part 2',
2011,
'https://m.media-amazon.com/images/M/MV5BMGVmMWNiMDktYjQ0Mi00MWIxLTk0N2UtN2ZlYTdkN2IzNDNlXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg',
'David Yates',
'Daniel Radcliffe, Emma Watson',
'Fantasy, Mistery'),
('Harry Potter and the Sorcerer''s Stone',
2001,
'https://m.media-amazon.com/images/M/MV5BNjQ3NWNlNmQtMTE5ZS00MDdmLTlkZjUtZTBlM2UxMGFiMTU3XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
'Chris Columbus',
'Daniel Radcliffe, Emma Watson',
'Fantasy, Mistery'),
('Harry Potter and the Chamber of Secrets',
2002,
'https://m.media-amazon.com/images/M/MV5BMTcxODgwMDkxNV5BMl5BanBnXkFtZTYwMDk2MDg3._V1_SX300.jpg',
'Chris Columbus',
'Daniel Radcliffe, Emma Watson',
'Fantasy, Mistery'),
('Harry Potter and the Prisoner of Azkaban',
2004,
'https://m.media-amazon.com/images/M/MV5BMTY4NTIwODg0N15BMl5BanBnXkFtZTcwOTc0MjEzMw@@._V1_SX300.jpg',
'Alfonso Cuarón',
'Daniel Radcliffe, Emma Watson',
'Fantasy, Mistery'),
('Harry Potter and the Goblet of Fire',
2005,
'https://m.media-amazon.com/images/M/MV5BMTI1NDMyMjExOF5BMl5BanBnXkFtZTcwOTc4MjQzMQ@@._V1_SX300.jpg',
'Mike Newell',
'Daniel Radcliffe, Emma Watson',
'Fantasy, Mistery')

TRUNCATE TABLE Movie

INSERT INTO Movie(title, year, posterurl, director, casts, genre)
VALUES 
('Blade Runner 2049',
2017,
'https://r2.easyimg.io/rma1k4o7c/bladerunner.jpg',
'Denis Villeneuve',
'Harrison Ford, Ryan Gosling',
'Action, Drama'),
('Barbie',
2023,
'https://r2.easyimg.io/rma1k4o7c/barbie.jpg',
'Greta Gerwig',
'Margot Robbie, Ryan Gosling',
'Adventure, Fantasy'),
('Jurassic World',
2015,
'https://r2.easyimg.io/rma1k4o7c/jurassic-world.jpg',
'Colin Trevorrow',
'Chris Pratt, Bryce Dallas Howard',
'Action, Adventure'),
('Star Wars: Episode IX - The Rise of Skywalker',
2019,
'https://r2.easyimg.io/rma1k4o7c/star-wars.jpg',
'J.J. Abrams',
'Daisy Ridley, John Boyega',
'Fantasy, Action'),
('La La Land',
2016,
'https://r2.easyimg.io/rma1k4o7c/lalaland.jpg',
'Damien Chazelle',
'Emma Stone, Ryan Gosling',
'Drama, Comedy'),
('Avengers: Endgame',
2019,
'https://r2.easyimg.io/me3e8p18l/avengers.jpg',
'Anthony Russo',
'Robert Downey Jr, Mark Ruffalo',
'Action, Drama'),
('Oppenheimer',
2023,
'https://r2.easyimg.io/51ubxb2wu/oppenheimer.jpg',
'Christopher Nolan',
'Cillian Murphy, Matt Damon', 
'Drama, History'),
('Guardians of the Galaxy',
2014,
'https://r2.easyimg.io/51ubxb2wu/guardians-galaxy.jpg',
'James Gunn',
'Chriss Pratt, Vin Diesel',
'Action, Adventure')